apiVersion: apps/v1
kind: Deployment
metadata:
    name: project-name
spec:
    selector:
        matchLabels:
            app: project-name
    replicas: 1
    template:
        metadata:
            labels:
                app: project-name
        spec:
            containers:
                - name: project-name
                  imagePullPolicy: Never
                  image: project.name:latest
                  readinessProbe:
                      httpGet:
                        path: /health
                        port: 3000
                      failureThreshold: 12
                      periodSeconds: 10
                  resources:
                      limits:
                          cpu: 50m
                          memory: 100Mi
                      requests:
                          cpu: 25m
                          memory: 10Mi
                  ports:
                      - containerPort: 3000
                  envFrom:
                      - secretRef:
                            name: dot-env
---
apiVersion: v1
kind: Service
metadata:
    name: project-name
spec:
    type: NodePort
    selector:
        app: project-name
    ports:
        - port: 8080
          targetPort: 3000
