name: build-project

on:
  pull_request:
    branches:
      - development

jobs:
  build:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout Branch
        uses: actions/checkout@v2
      - name: Build Project
        uses: ./.github/actions
